/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, update the JSONSchema referenced in
 * ingestPrimitives.js, and run `npm run ingest_primitives` to regenerate this file.
 */

/**
 * The ID of the Shipment
 */
export type ShipmentUuid = string;
/**
 * SCAC code of the carrier.
 */
export type CarriersScac = string;
/**
 * SCAC code of the frieght forwarder.
 */
export type ForwardersScac = string;
/**
 * SCAC code of the Non-Vessel Operating Common Carrier.
 */
export type NvocCsScac = string;
/**
 * Reference number of this shipment assigned by the Shipper
 */
export type ShippersReferenceNumber = string;
/**
 * Reference number of this shipment assigned by the Forwarder
 */
export type ForwardersReferenceNumber = string;
/**
 * ID of the Shipper assigned by the Forwarder
 */
export type ForwardersIdAssignedToTheShipper = string;
/**
 * The ID of the Location
 */
export type LocationUuid = string;
/**
 * The name of the Location
 */
export type LocationName = string;
/**
 * The first line of the location's address
 */
export type Address1 = string;
/**
 * The second line of the location's address
 */
export type Address2 = string;
/**
 * The city of the location
 */
export type City = string;
/**
 * The state of the location
 */
export type State = string;
/**
 * The country of the location
 */
export type Country = string;
/**
 * The postal/zip code of the location
 */
export type PostalCode = string;
/**
 * Phone number of the location's primary contact
 */
export type PhoneNumber = string;
/**
 * Fax number of the location's primary contact
 */
export type FaxNumber = string;
/**
 * Timestamp of the last update
 */
export type UpdatedAt = string;
/**
 * Timestamp of the object creation
 */
export type CreatedAt = string;
/**
 * Shipper's instructions to the carrier
 */
export type SpecialInstructions = string;
/**
 * Progressive Number for shipment tracking
 */
export type ProNumberForTruckShipment = string;
/**
 * The master Bill of Lading Number
 */
export type MasterBillOfLadingNumber = string;
/**
 * The House Bill of Lading Number
 */
export type HouseBillOfLadingNumber = string;
/**
 * The Sub-House Bill of Lading Number
 */
export type SubHouseBillOfLadingNumber = string;
/**
 * The payment terms for the Shipment
 */
export type PaymentTerms = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheVesselNameSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheVoyageNumberSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheModeSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheNumberOfPackagesSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheGrossWeightKgsSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheVolumeCbmsSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheContainerCountSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDimensionalWeightSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheChargeableWeightSchema = number;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDocsReceivedActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDocsApprovedActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type ThePickupAppointmentActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type ThePickupEstimatedSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type ThePickupActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheLoadingEstimatedSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheLoadingActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDepartureEstimatedSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDepartureActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDeliveryAppointmentActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheArrivalPortEstimatedSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheArrivalPortActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDeliveryEstimatedSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheDeliveryActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheLastAttemptedDeliveryActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCancelRequestedDateActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCancelConfirmedDateActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCustomsFiledDateActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCustomsHoldDateActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCustomsReleaseDateActualSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheContainerizationTypeSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheArrivalUnlocodeSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheFinalPortUnlocodeSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheImportUnlocodeSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheLadingUnlocodeSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheOriginUnlocodeSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheUsRoutedExportSchema = boolean;
/**
 * An explanation about the purpose of this instance.
 */
export type TheImportCustomsModeSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheUsCustomsExportPortSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheUsCustomsImportPortSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheUpdatedAtSchema = string;
/**
 * An explanation about the purpose of this instance.
 */
export type TheCreatedAtSchema = string;

export interface Shipment {
    id: ShipmentUuid;
    carrier_scac?: CarriersScac;
    forwarder_scac?: ForwardersScac;
    nvocc_scac?: NvocCsScac;
    shipper_reference?: ShippersReferenceNumber;
    forwarder_reference?: ForwardersReferenceNumber;
    forwarders_shipper_id?: ForwardersIdAssignedToTheShipper;
    ship_from_location?: ShipFromAddress;
    ship_to_location?: ShipToAddress;
    final_destination_location?: ShipmentFinalDestination;
    carrier_instructions?: SpecialInstructions;
    pro_number?: ProNumberForTruckShipment;
    master_bill?: MasterBillOfLadingNumber;
    house_bill?: HouseBillOfLadingNumber;
    subhouse_bill?: SubHouseBillOfLadingNumber;
    freight_payment_terms?: PaymentTerms;
    vessel_name?: TheVesselNameSchema;
    voyage_number?: TheVoyageNumberSchema;
    mode?: TheModeSchema;
    number_of_packages?: TheNumberOfPackagesSchema;
    gross_weight_kgs?: TheGrossWeightKgsSchema;
    volume_cbms?: TheVolumeCbmsSchema;
    container_count?: TheContainerCountSchema;
    dimensional_weight?: TheDimensionalWeightSchema;
    chargeable_weight?: TheChargeableWeightSchema;
    docs_received_actual?: TheDocsReceivedActualSchema;
    docs_approved_actual?: TheDocsApprovedActualSchema;
    pickup_appointment_actual?: ThePickupAppointmentActualSchema;
    pickup_estimated?: ThePickupEstimatedSchema;
    pickup_actual?: ThePickupActualSchema;
    loading_estimated?: TheLoadingEstimatedSchema;
    loading_actual?: TheLoadingActualSchema;
    departure_estimated?: TheDepartureEstimatedSchema;
    departure_actual?: TheDepartureActualSchema;
    delivery_appointment_actual?: TheDeliveryAppointmentActualSchema;
    arrival_port_estimated?: TheArrivalPortEstimatedSchema;
    arrival_port_actual?: TheArrivalPortActualSchema;
    delivery_estimated?: TheDeliveryEstimatedSchema;
    delivery_actual?: TheDeliveryActualSchema;
    last_attempted_delivery_actual?: TheLastAttemptedDeliveryActualSchema;
    cancel_requested_date_actual?: TheCancelRequestedDateActualSchema;
    cancel_confirmed_date_actual?: TheCancelConfirmedDateActualSchema;
    customs_filed_date_actual?: TheCustomsFiledDateActualSchema;
    customs_hold_date_actual?: TheCustomsHoldDateActualSchema;
    customs_release_date_actual?: TheCustomsReleaseDateActualSchema;
    containerization_type?: TheContainerizationTypeSchema;
    arrival_unlocode?: TheArrivalUnlocodeSchema;
    final_port_unlocode?: TheFinalPortUnlocodeSchema;
    import_unlocode?: TheImportUnlocodeSchema;
    lading_unlocode?: TheLadingUnlocodeSchema;
    origin_unlocode?: TheOriginUnlocodeSchema;
    us_routed_export?: TheUsRoutedExportSchema;
    import_customs_mode?: TheImportCustomsModeSchema;
    us_customs_export_port?: TheUsCustomsExportPortSchema;
    us_customs_import_port?: TheUsCustomsImportPortSchema;
    updated_at?: TheUpdatedAtSchema;
    created_at?: TheCreatedAtSchema;
    customer_fields?: {
        [k: string]: any;
    };
}
/**
 * The Shipment's ship-from address
 */
export interface ShipFromAddress {
    id: LocationUuid;
    name?: LocationName;
    address_1?: Address1;
    address_2?: Address2;
    city?: City;
    state?: State;
    country?: Country;
    postal_code?: PostalCode;
    phone_number?: PhoneNumber;
    fax_number?: FaxNumber;
    updated_at?: UpdatedAt;
    created_at?: CreatedAt;
}
/**
 * The Shipment's ship-to address
 */
export interface ShipToAddress {
    id: LocationUuid;
    name?: LocationName;
    address_1?: Address1;
    address_2?: Address2;
    city?: City;
    state?: State;
    country?: Country;
    postal_code?: PostalCode;
    phone_number?: PhoneNumber;
    fax_number?: FaxNumber;
    updated_at?: UpdatedAt;
    created_at?: CreatedAt;
}
/**
 * The Shipment's Final Destination address
 */
export interface ShipmentFinalDestination {
    id: LocationUuid;
    name?: LocationName;
    address_1?: Address1;
    address_2?: Address2;
    city?: City;
    state?: State;
    country?: Country;
    postal_code?: PostalCode;
    phone_number?: PhoneNumber;
    fax_number?: FaxNumber;
    updated_at?: UpdatedAt;
    created_at?: CreatedAt;
}
