# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.21.0
    environment:
      ROLE: circleci

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Setup Docker network
          command: |
            docker network ls | grep portal > /dev/null || docker network create portal

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip bash
            pip install awscli

      - run:
          name: Build application Docker images
          command: |
            docker build --target test   --tag engine-node-test .
            docker build --target deploy --tag engine-node-deploy --cache-from engine-node-test .

      - run:
          name: Launch the docker containers
          command: |
            bin/dc up -d rpc

      - run:
          name: Run lint for JUnit
          command: |
            bin/dc exec -T rpc yarn lint-junit

      - run:
          name: Run lint for HTML
          command: |
            bin/dc exec -T rpc yarn lint-html

      - run:
          name: Run unit tests
          command: |
            bin/dc exec -T rpc yarn test

      - run:
          name: Copy artifacts from Docker
          command: |
            docker cp $(bin/dc ps -q rpc):/app/reports/. reports

      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports

      - run:
          name: Save docker image
          command: |
            mkdir -p docker-cache
            docker save -o docker-cache/built-image.tar engine-node-deploy

      - save_cache:
          key: docker-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - docker-cache

  push-to-ecr:
    docker:
      - image: docker:stable-git

    steps:
      - restore_cache:
          keys:
            - docker-cache-{{ .Branch }}-{{ .Revision }}

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Set dynamic ENV variables
          command: |
            echo 'export SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
            pip install awscli

      - run:
          name: Load docker image
          command: |
            docker load < /root/repo/docker-cache/built-image.tar

      - run:
          name: Push image to ECR
          command: |
            source $BASH_ENV
            docker tag engine-node-deploy $ECR_ENDPOINT/engine-node:$SHORT_GIT_HASH
            docker tag engine-node-deploy $ECR_ENDPOINT/engine-node:latest
            $(aws ecr get-login --no-include-email)
            docker push $ECR_ENDPOINT/engine-node:$SHORT_GIT_HASH
            docker push $ECR_ENDPOINT/engine-node:latest

  deploy-to-dev:
    docker:
      - image: docker:stable-git

    steps:
      - run:
          name: Set dynamic ENV variables
          command: |
            echo 'export SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
            pip install awscli

      - run:
          name: Deploy new Task Revision to ECS
          command: |
            source $BASH_ENV
            aws lambda invoke --function-name DeployImageToECS --payload "{
                \"app\": \"engine\",
                \"env\": \"DEV\",
                \"image\": \"$ECR_ENDPOINT/engine-node:$SHORT_GIT_HASH\"
              }" outputfile.txt && cat outputfile.txt

  deploy-to-stage:
    docker:
      - image: docker:stable-git

    steps:
      - run:
          name: Set dynamic ENV variables
          command: |
            echo 'export SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
            pip install awscli

      - run:
          name: Deploy new Task Revision to ECS
          command: |
            source $BASH_ENV
            aws lambda invoke --function-name DeployImageToECS --payload "{
                \"app\": \"engine\",
                \"env\": \"STAGE\",
                \"image\": \"$ECR_ENDPOINT/engine-node:$SHORT_GIT_HASH\"
              }" outputfile.txt && cat outputfile.txt

  deploy-to-demo:
    docker:
    - image: docker:stable-git

    steps:
    - run:
        name: Set dynamic ENV variables
        command: |
          echo 'export SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV

    - run:
        name: Install dependencies
        command: |
          apk add --no-cache py-pip
          pip install awscli

    - run:
        name: Deploy new Task Revision to ECS
        command: |
          source $BASH_ENV
          aws lambda invoke --function-name DeployImageToECS --payload "{
              \"app\": \"engine\",
              \"env\": \"DEMO\",
              \"image\": \"$ECR_ENDPOINT/engine-node:$SHORT_GIT_HASH\"
            }" outputfile.txt && cat outputfile.txt

  deploy-to-prod:
    docker:
      - image: docker:stable-git

    steps:
      - run:
          name: Set dynamic ENV variables
          command: |
            echo 'export SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
            pip install awscli

      - run:
          name: Deploy new Task Revision to ECS
          command: |
            source $BASH_ENV
            aws lambda invoke --function-name DeployImageToECS --payload "{
                \"app\": \"engine\",
                \"env\": \"PROD\",
                \"image\": \"$ECR_ENDPOINT/engine-node:$SHORT_GIT_HASH\"
              }" outputfile.txt && cat outputfile.txt

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - push-to-ecr:
          filters:
            branches:
              only: master
          requires:
            - build
      - deploy-to-dev:
          filters:
            branches:
              only: master
          requires:
            - push-to-ecr
      - hold-deploy-stage:
          filters:
            branches:
              only: master
          type: approval
          requires:
            - push-to-ecr
      - deploy-to-stage:
          filters:
            branches:
              only: master
          requires:
            - hold-deploy-stage
      - hold-deploy-demo:
          filters:
            branches:
              only: master
          type: approval
          requires:
            - deploy-to-dev
      - deploy-to-demo:
          filters:
            branches:
              only: master
          requires:
            - hold-deploy-demo
      - hold-deploy-prod:
          filters:
            branches:
              only: master
          type: approval
          requires:
            - deploy-to-stage
      - deploy-to-prod:
          filters:
            branches:
              only: master
          requires:
            - hold-deploy-prod
