// https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables

export default {
  "Storage": {
    "SFTP": {
      "SFTP_HOST": "SFTP_HOST",
      "SFTP_PORT": "SFTP_PORT",
      "SFTP_USER": "SFTP_USER",
      "SFTP_PASS": "SFTP_PASS",
      "SFTP_DRIVER_TESTS": "SFTP_DRIVER_TESTS"
    },
    "S3": {
      "S3_ENDPOINT": "S3_ENDPOINT",
      "S3_BUCKET": "S3_BUCKET",
      "S3_ACCESSKEY": "S3_ACCESSKEY",
      "S3_SECRETKEY": "S3_SECRETKEY",
      "S3_DRIVER_TESTS": "S3_DRIVER_TESTS"
    }
  },
  "DATABASE_URL": "DATABASE_URL",
  "ELASTICSEARCH_URL": "ELASTICSEARCH_URL",
  "ETHERSCAN_API_KEY": "ETHERSCAN_API_KEY",
  "ES_TEST_NODE_URL": "ES_TEST_NODE_URL",
  "FORCE_LATEST_LOAD_CONTRACT_VERSION" : "FORCE_LATEST_LOAD_CONTRACT_VERSION",
  "FORCE_LATEST_NOTARY_CONTRACT_VERSION" : "FORCE_LATEST_NOTARY_CONTRACT_VERSION",
  "GETH_NODE": "GETH_NODE",
  "GETH_NETWORK": "GETH_NETWORK",
  "INFLUXDB_URL": "INFLUXDB_URL",
  "INFURA_PROJECT_ID": "INFURA_PROJECT_ID",
  "REDIS_URL": "REDIS_URL",
  "USE_JS_ORM_ENTITIES": "USE_JS_ORM_ENTITIES",
  "LOOM_CONFIG": {
    "ENABLED": "LOOM_ENABLED",
    "CHAIN_ID_STRING": "LOOM_CHAIN_ID_STRING",
    "CHAIN_ID_NUMBER": "LOOM_CHAIN_ID_NUMBER",
    "DEPLOY_KEY": "LOOM_DEPLOY_KEY",
  },
}
