version: '3.4'
services:


  redis_db:
    image: redis
    command: >
      --requirepass redis_pass --appendonly yes
    expose:
      - 6379


  geth-poa:
#    image: shipchain/geth-poa
#    image: shipchain/geth-poa:v1.9.2
    image: trufflesuite/ganache-cli
    command: ganache-cli -l 8000000
    expose:
      - 8545
    environment:
      GETH_VERBOSITY: 1


  sftp:
    image: atmoz/sftp
    command: shipchain_user:shipchain_password:::upload
    expose:
      - 22


  minio:
    image: minio/minio
    command: server /data
    ports:
      - 9099:9000
    environment:
      MINIO_ACCESS_KEY: myMinioAccessKey
      MINIO_SECRET_KEY: myMinioSecretKey


  psql:
    image: sameersbn/postgresql:9.6-2
    expose:
      - 5432
    environment:
      DB_NAME: engine
      DB_PASS: engine
      DB_USER: engine
      DB_EXTENSION: '"uuid-ossp"'


  rpc:
    build:
      context: ../
      target: build
    image: engine-node-build
    command: yarn develop
    ports:
      - 2000:2000
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DATABASE_URL
      - ELASTICSEARCH_URL
      - ENV
      - GETH_NETWORK
      - GETH_NODE
      - INFLUXDB_URL
      - LOCAL_SECRET_KEY
      - LOGGING_LEVEL
      - REDIS_URL
      - SERVICE=engine-rpc
    networks:
      default:
        aliases:
          - engine-rpc
      portal:
        aliases:
          - engine-rpc


networks:
  portal:
    external: true
