version: '2.1'
services:

  geth-poa:
    image: shipchain/geth-poa
    healthcheck:
      test: "nc -z localhost 8545"
      timeout: 10s
      interval: 10s
      retries: 3
    expose:
      - '8545'

  sftp:
    image: atmoz/sftp
    expose:
      - '22'
    command: shipchain_user:shipchain_password:::upload

  psql:
    image: sameersbn/postgresql:9.6-2
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "engine"]
      interval: 1s
      timeout: 3s
      retries: 30
    expose:
      - '5432'
    environment:
    - DB_NAME=engine
    - DB_PASS=engine
    - DB_USER=engine
    - DB_EXTENSION="uuid-ossp"
    volumes:
    - /data/shipchain/engine/postgresql:/var/lib/postgresql

  rpc:
    extends:
      service: engine-node
      file: build.yml
    command: sleep infinity
    links:
      - geth-poa
      - psql
      - sftp
    depends_on:
      geth-poa:
        condition: service_healthy
      psql:
        condition: service_healthy
    environment:
      - ENV
      - GETH_NODE
      - SERVICE=engine-app
      - SFTP_DRIVER_TESTS
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - SFTP_USER=shipchain_user
      - SFTP_PASS=shipchain_password
      - S3_DRIVER_TESTS
      - S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - LOCAL_SECRET_KEY
      - REDIS_URL
