version: '2.1'
services:


  elasticsearch:
    image: sebp/elk
    healthcheck:
      test: "curl -fsSL http://localhost:9200/_cat/health\\?h\\=status | sed -r 's/^[[:space:]]+|[[:space:]]+$$//g' | grep -q green"
      interval: 3s
      timeout: 3s
      retries: 30
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
    networks:
      default:
        aliases:
          - engine-elasticsearch
      portal:
        aliases:
          - engine-elasticsearch
    environment:
      - ES_HEAP_SIZE=2g
      - SERVICE=engine-elasticsearch


  rpc:
    command: sleep infinity
    links:
      - redis_db
      - geth-poa
      - elasticsearch
      - sftp
      - minio
      - psql

    depends_on:
      redis_db:
        condition: service_healthy
      geth-poa:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      minio:
        condition: service_healthy
      psql:
        condition: service_healthy
    environment:
      - ES_TEST_NODE_URL=http://elasticsearch:9200
      - GETH_NODE=http://geth-poa:8545
      - SFTP_DRIVER_TESTS
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - SFTP_USER=shipchain_user
      - SFTP_PASS=shipchain_password
      - S3_DRIVER_TESTS
      - S3_BUCKET=my-test-bucket
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESSKEY=myMinioAccessKey
      - S3_SECRETKEY=myMinioSecretKey
