version: '3.4'
services:


  rpc:
    build:
      context: ../
      target: test
    image: engine-node-test
    command: sleep infinity
    links:
      - redis_db
      - geth-poa
      - sftp
      - minio
      - psql
    environment:
      - GETH_NODE=http://geth-poa:8545
      - SFTP_DRIVER_TESTS
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - SFTP_USER=shipchain_user
      - SFTP_PASS=shipchain_password
      - S3_DRIVER_TESTS
      - S3_BUCKET=my-test-bucket
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESSKEY=myMinioAccessKey
      - S3_SECRETKEY=myMinioSecretKey
