version: '3.4'
services:


  elasticsearch:
    image: sebp/elk
    ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
    networks:
      default:
        aliases:
          - engine-elasticsearch
      portal:
        aliases:
          - engine-elasticsearch
    environment:
      - ES_HEAP_SIZE=2g
      - SERVICE=engine-elasticsearch


  rpc:
    build:
      context: ../
      target: test
    image: engine-node-test
    #    command: sleep infinity
    command: sh -c 'while sleep 3600; do :; done'
    links:
      - redis_db
      - loom
      - elasticsearch
      - sftp
      - minio
      - psql
    environment:
      - ENV=test
      - ES_TEST_NODE_URL=http://elasticsearch:9200
      - SFTP_DRIVER_TESTS
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - SFTP_USER=shipchain_user
      - SFTP_PASS=shipchain_password
      - S3_DRIVER_TESTS
      - S3_BUCKET=my-test-bucket
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESSKEY=myMinioAccessKey
      - S3_SECRETKEY=myMinioSecretKey
      - GETH_NODE=http://loom:46658/eth
      - LOOM_ENABLED=true
      - LOOM_CHAIN_ID_STRING=default
      - LOOM_CHAIN_ID_NUMBER=3657971041736948
      - LOOM_DEPLOY_KEY=0x0000000000000000000000000000000000000000000000000000000000000001

