version: '2.1'
services:


  redis_db:
    volumes:
      - /data/shipchain/engine/redis:/data


  geth-poa:
    volumes:
      - /data/shipchain/engine/chain:/geth/chain


  minio:
    volumes:
      - /data/shipchain/engine/minio:/data
      - /data/shipchain/engine/minioconfig:/root/.minio


  psql:
    volumes:
      - /data/shipchain/engine/postgresql:/var/lib/postgresql


  rpc:
    links:
      - psql
      - sftp
      - minio
      - geth-poa
      - redis_db
    volumes:
      - ../:/app
    environment:
      - GETH_NODE=http://geth-poa:8545
