version: '3.4'
services:


  redis_db:
    volumes:
      - /data/shipchain/engine/redis:/data


  geth-poa:
    volumes:
      - /data/shipchain/engine/chain:/geth/chain


  loom:
    volumes:
      - /data/shipchain/engine/loom.data:/app/chaindata/data
      - /data/shipchain/engine/loom.app.db:/app/app.db
      - /data/shipchain/engine/loom.evm.db:/app/evm.db
      - /data/shipchain/engine/loom.receipts_db:/app/receipts_db


  minio:
    volumes:
      - /data/shipchain/engine/minio:/data
      - /data/shipchain/engine/minioconfig:/root/.minio


  psql:
    volumes:
      - /data/shipchain/engine/postgresql:/var/lib/postgresql


  influxdb:
    image: influxdb:alpine
    command: "influxd"
    expose:
      - 8083
      - 8086
      - 8090
    links:
      - grafana
    volumes:
      - /data/shipchain/engine/influxdbtest:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=engine
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=engine
      - INFLUXDB_USER_PASSWORD=engine

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /data/shipchain/engine/grafanatest:/var/lib/grafana
    user: 0:0


  rpc:
    links:
      - psql
      - sftp
      - minio
      - loom
      - redis_db
      - influxdb
    volumes:
      - ../:/app
    environment:
      - GETH_NODE=http://loom:46658/eth
      - INFLUXDB_URL=http://influxdb:8086/engine
      - LOOM_ENABLED=true
      - LOOM_CHAIN_ID_STRING=default
      - LOOM_CHAIN_ID_NUMBER=3657971041736948
      - LOOM_DEPLOY_KEY=0x0000000000000000000000000000000000000000000000000000000000000001
