version: '2.1'
services:

  geth-poa:
    image: shipchain/geth-poa
    healthcheck:
      test: "nc -z localhost 8545"
      timeout: 10s
      interval: 10s
      retries: 3
    volumes:
    - /data/shipchain/engine/chain:/geth/chain
    expose:
      - '8545'
    environment:
      - GETH_VERBOSITY=1

  sftp:
      image: atmoz/sftp
      ports:
          - "2222:22"
      command: shipchain_user:shipchain_password:::upload

  psql:
    image: sameersbn/postgresql:9.6-2
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "engine"]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
    - "5431:5432"
    environment:
      - DB_NAME=engine
      - DB_PASS=engine
      - DB_USER=engine
      - DB_EXTENSION="uuid-ossp"
    volumes:
    - /data/shipchain/engine/postgresql:/var/lib/postgresql

  rpc:
    extends:
      service: engine-node
      file: build.yml
    command: nodemon -e "ts" -x "ts-node" rpc-server.ts
    ports:
      - "2000:2000"
    networks:
      default:
        aliases:
          - engine-rpc
      portal:
        aliases:
          - engine-rpc
    links:
      - psql
      - geth-poa
      - sftp
    depends_on:
      geth-poa:
        condition: service_healthy
      psql:
        condition: service_healthy
    volumes:
      - ../:/app
    environment:
      - ENV
      - GETH_NODE=http://geth-poa:8545
      - SERVICE=engine-rpc
      - DATABASE_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - ELASTICSEARCH_URL
      - INFLUXDB_URL
      - LOCAL_SECRET_KEY
      - LOGGING_LEVEL

networks:
  portal:
    external: true
