version: '3.4'
services:


  redis_db:
    volumes:
      - /data/shipchain/engine/redis:/data


  ropsten:
    image: ethereum/client-go:v1.8.20
    command: --testnet --syncmode light --rpc --rpcport 8545 --rpcaddr 0.0.0.0 --rpccorsdomain * --rpcvhosts * --verbosity 2
    expose:
      - 8545


  psql:
    volumes:
      - /data/shipchain/engine/postgresql:/var/lib/postgresql


  rpc:
    build:
      context: ../
      target: prod
    image: engine-node-prod
    command: node_modules/.bin/ts-node rpc-server.ts
    links:
      - psql
      - ropsten
      - redis_db
    environment:
      - GETH_NETWORK=ropsten
      - GETH_NODE=http://ropsten:8545
      - GETH_NAME=ropsten
